--------------------------------------------------------
--  Fichier cr�� - vendredi-d�cembre-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROMO
--------------------------------------------------------

  CREATE TABLE "ANAS"."PROMO" 
   (	"CIN" NUMBER, 
	"POURCENTAGE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"DATEDEBUT" DATE, 
	"DATEFIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ANAS.PROMO
SET DEFINE OFF;
Insert into ANAS.PROMO (CIN,POURCENTAGE,NOM,DATEDEBUT,DATEFIN) values (145,2,'hama',null,null);
Insert into ANAS.PROMO (CIN,POURCENTAGE,NOM,DATEDEBUT,DATEFIN) values (56412,2,'mmlkj',null,null);
Insert into ANAS.PROMO (CIN,POURCENTAGE,NOM,DATEDEBUT,DATEFIN) values (123123123,1,'mmm',null,null);
Insert into ANAS.PROMO (CIN,POURCENTAGE,NOM,DATEDEBUT,DATEFIN) values (11111,1,'zizo',to_date('01-01-00','DD-MM-RR'),to_date('03-01-00','DD-MM-RR'));
--------------------------------------------------------
--  DDL for Index PROMO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANAS"."PROMO_PK" ON "ANAS"."PROMO" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PROMO
--------------------------------------------------------

  ALTER TABLE "ANAS"."PROMO" ADD CONSTRAINT "PROMO_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANAS"."PROMO" MODIFY ("POURCENTAGE" NOT NULL ENABLE);
  ALTER TABLE "ANAS"."PROMO" MODIFY ("CIN" NOT NULL ENABLE);
