--------------------------------------------------------
--  Fichier créé - vendredi-décembre-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PUBLICITE
--------------------------------------------------------

  CREATE TABLE "ANAS"."PUBLICITE" 
   (	"IDENTIFIANT" NUMBER, 
	"NOM" VARCHAR2(30 BYTE), 
	"PRIX" FLOAT(126), 
	"DUREE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"CHAINE" VARCHAR2(30 BYTE)
   ); SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ANAS.PUBLICITE
SET DEFINE OFF;
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (5555555,'hhjkl',4,10,'Audio','iii');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (3,'mou',0,20,'AudioVisuel','krjhjrgher');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (4,'ahmed',100,10,'audio','ifm');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (5,'mou',450.3,10,'audio','mosaique');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (6,'test246',0,1,'audio','ifm');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (7,'test2465',0,1,'audio','ifm');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (8,'test2465',1225,1,'audio','ifm');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (5464,'azzz',123,2,'opm','mplkj');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (10,'klmm',0,15,'visuel','tf1');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (21,'ayoub',100.3,20,'audiviselle','elhiwar');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (22,'ayoub',100.3,20,'audiviselle','elhiwar');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (25345566,'lom',123,2,'opm','mplkj');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (253,'lom',123,2,'opm','mplkj');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (54646,'azzz',123,2,'opm','mplkj');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (654321,'ANAS',100.3,0,'audio','IFM');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (225369785,'uuu',4,3,'AudioVisuel','uuu');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (222,'qsdfg',3,1,'RÃ©seauSocial','dfghjk');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (1,'kkk',4,9,'RÃ©seauSocial','facebook');
Insert into ANAS.PUBLICITE (IDENTIFIANT,NOM,PRIX,DUREE,TYPE,CHAINE) values (3636,'aaaa',3,2,'AudioVisuel','mmmm');
--------------------------------------------------------
--  DDL for Index PUBLICITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANAS"."PUBLICITE_PK" ON "ANAS"."PUBLICITE" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger 1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ANAS"."1" 
BEFORE INSERT ON PUBLICITE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDENTIFIANT IS NULL THEN
      SELECT "1".NEXTVAL INTO :NEW.IDENTIFIANT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ANAS"."1" ENABLE;
--------------------------------------------------------
--  Constraints for Table PUBLICITE
--------------------------------------------------------

  ALTER TABLE "ANAS"."PUBLICITE" ADD CONSTRAINT "PUBLICITE_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANAS"."PUBLICITE" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
